name: Pre-deployment checks

on: [push, pull_request]

env:
  DATABASE_URL: "https://url.com"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "secret_key"
  CLERK_SECRET_KEY: "secret_key"
  UPSTASH_REDIS_REST_URL: "https://url.com"
  UPSTASH_REDIS_REST_TOKEN: "secret_token"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Integration tests
        run: npm run test
